### PR TITLE
Updating unique_table_sync_key to address incremental unique test fail

### PR DESCRIPTION
**Pull request by JustMaris**
Proposing a change for an easy fix

**Please provide your name and company**
Maris Popens, Easypark

**Link the issue/feature request which this PR is meant to address**

https://github.com/fivetran/dbt_fivetran_log/issues/90

**Detail what changes this PR introduces and how this addresses the issue/feature request linked above.**

Implementing what the issue describes and what was discussed under the issue.

**How did you validate the changes introduced within this PR?**

**Which warehouse did you use to develop these changes?**

**Did you update the CHANGELOG?**

- [ ] Yes
- [x] No

**Did you update the dbt_project.yml files with the version upgrade (please leverage standard semantic versioning)? (In both your main project and integration_tests)**

- [ ] Yes
- [x] No

**Provide an emoji that best describes your current mood**
 
😪 

**Feedback**

We are so excited you decided to contribute to the Fivetran community dbt package! We continue to work to improve the packages and would greatly appreciate your [feedback](https://www.surveymonkey.com/r/DQ7K7WW) on our existing dbt packages or what you'd like to see next.

**PR Template** 
- [Community Pull Request Template](?expand=1&template=pull_request_template.md) (default)

- [Maintainer Pull Request Template](?expand=1&template=maintainer_pull_request_template.md) (to be used by maintainers)

### CODE REVIEW

**Comment by fivetran-joemarkiewicz** [comment]
Hi @JustMaris thank you for opening this PR! I will review this today and let you know if I have any questions. 

Would you be comfortable with me making updates directly to this branch? Most likely nothing major, just some under the hood updates to prepare the branch for release.

**Comment by JustMaris** [comment]
> Hi @JustMaris thank you for opening this PR! My team will review this today and let you know if I have any questions. 
> 
> Would you be comfortable with me making updates directly to this branch? Most likely nothing major, just some under the hood updates to prepare the branch for release.

That's completely fine. I didn't know everything that needs to be done, and due to that didn't do everything that needs to be done.

**Review by fivetran-joemarkiewicz — APPROVED** [review]
@JustMaris thanks again for opening this PR to address the open issue of the unique key in the end model. I have just been able to review your changes and they look great! I made some additional under the hood updates to ensure this will be ready to merge and release.

This will result in the `v1.2.0` release of the fivetran platform package. As we are changing the unique key of an incremental model we will need to make this a major update in order to ensure users capture the changes in a full refresh. 

Thanks again and I will push this forward for to our internal release process. You should see this live within the week. 😄

**Comment by JustMaris** [comment]
> @JustMaris thanks again for opening this PR to address the open issue of the unique key in the end model. I have just been able to review your changes and they look great! I made some additional under the hood updates to ensure this will be ready to merge and release.
> 
> This will result in the `v1.2.0` release of the fivetran platform package. As we are changing the unique key of an incremental model we will need to make this a major update in order to ensure users capture the changes in a full refresh. 
> 
> Thanks again and I will push this forward for to our internal release process. You should see this live within the week. 😄 

Glad to hear that. Looking forward to the release, to have one less uniqueness test to address. 😃

**Pull request merged**
